# Generated by Django 4.1 on 2022-09-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('notio_token', models.CharField(max_length=200)),
                ('page_id', models.CharField(max_length=200)),
                ('next_curser', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promo')),
            ],
        ),
    ]
