# Generated by Django 4.1 on 2022-09-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='notio_token',
            new_name='notion_token',
        ),
    ]
