# Generated by Django 4.1 on 2022-09-17 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_promo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
