# Generated by Django 4.1 on 2022-09-17 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_promo_notion_token_alter_promo_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='level',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
