# Generated by Django 4.1 on 2022-09-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_promo_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='next_curser',
            new_name='next_cursor',
        ),
    ]
